[project]
name = "easydel"
version = "0.1.0.dev016"
description = "An open-source library to make training faster and more optimized in JAX"
authors = ["Erfan Zare Chavoshi <Erfanzare810@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.2,<0.116.0",
    "fjformer==0.0.91",
    "flax>=0.10.2",
    "jax[tpu]>=0.5.0",
    "jinja2>=3.1.5,<3.2.0",
    "optax>=0.2.2,<0.3.0",
    "prometheus_client>=0.21.0,<0.22.0",
    "termcolor",
    "torch>=2.5.0",
    "tqdm",
    "transformers>=4.47.0",
    "uvicorn>=0.32.0,<0.33.0",
    "uvloop>=0.21.0,<0.22.0",
    "wandb>=0.18.5,<0.19.0",
    # { version = "^4.9.6", optional = true, name = "tensorflow-datasets" },
    # { version = "^2.18.0", optional = true, name = "tensorflow-cpu" },
    # { version = "^2.18.0", optional = true, name = "tensorboard" },
    # { version = "^3.2.0", optional = true, name = "datasets" },
]
